name: High Priority Issue
description: 重大な問題の報告を行うテンプレート
title: "[High Priority Issue]: "
labels: 
  - bug
  - priority: high
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 重大な問題の説明
        重大な問題の概要を記述してください。緊急対応が必要な場合は、その理由も含めてください。

  - type: textarea
    id: critical_description
    attributes:
      label: 問題の説明
      description: 重大な問題の詳細を入力してください
      placeholder: "問題の詳細な説明を記入してください"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🔄 再現手順
        この問題を再現するための手順を明確に記載してください。

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 問題を再現するための手順を番号付きで記載してください
      placeholder: "例: 1. Go to '...', 2. Click on '...'"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 影響範囲
      description: この問題が影響を及ぼす機能や範囲について説明してください
      placeholder: "影響範囲を記入してください"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🖥️ 環境情報
        使用環境を記入してください

  - type: input
    id: environment_os
    attributes:
      label: OS
      description: 使用しているOSを記入してください
      placeholder: "例: Windows, macOS, Linux"

  - type: input
    id: environment_browser
    attributes:
      label: ブラウザ
      description: 使用しているブラウザを記入してください
      placeholder: "例: Chrome, Safari"
