name: High Priority Issue
description: 重要な問題の報告を行うテンプレート
title: "[High Priority Issue]: "
labels: 
  - issue
  - "🔥優先度：高"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 重要な問題の説明
        重要な問題の概要を記述してください。

  - type: textarea
    id: critical_description
    attributes:
      label: 問題の説明
      description: 重要な問題の詳細を入力してください
      placeholder: "問題の詳細な説明を記入してください"
    validations:
      required: true
