name: バグ報告
description: バグの報告を行う際のテンプレート
title: "[Bug] "
labels: 
  - bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグの説明
        バグの簡単な説明を入力してください

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: バグの簡単な説明を入力してください
      placeholder: "バグの詳細な説明を記入してください"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🔄 再現手順
        バグを再現するための手順を番号付きで記載してください

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: "バグを再現するための手順を番号付きで記載してください (例: 1. Go to '...', 2. Click on '...')"
      placeholder: "再現手順を記入してください"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🎯 期待される挙動
        正常な動作がどのようになるかを入力してください

  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待される挙動
      description: 正常な動作がどのようになるかを入力してください
      placeholder: "期待される挙動の詳細を記入してください"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📸 スクリーンショット
        必要に応じてスクリーンショットを追加してください

  - type: input
    id: screenshot
    attributes:
      label: スクリーンショットリンク
      description: 必要に応じてスクリーンショットのリンクを入力してください
      placeholder: "例: https://example.com/screenshot.png"

  - type: markdown
    attributes:
      value: |
        ## 🖥️ 環境
        お使いのOSやブラウザのバージョンなどを記載してください

  - type: input
    id: environment_os
    attributes:
      label: OS
      description: 使用しているOSを記入してください
      placeholder: "例: Windows, macOS, Linux"

  - type: input
    id: environment_browser
    attributes:
      label: ブラウザ
      description: 使用しているブラウザを記入してください
      placeholder: "例: Chrome, Safari"

  - type: input
    id: environment_version
    attributes:
      label: バージョン
      description: 使用しているバージョンを記入してください
      placeholder: "例: 22"

  - type: markdown
    attributes:
      value: |
        ## 📝 その他の情報
        その他、バグに関連する情報があれば記載してください

  - type: textarea
    id: additional_info
    attributes:
      label: その他の情報
      description: バグに関連する情報があれば記載してください
